@api = http://localhost:3000/tasks

GET {{api}}

###
GET {{api}}/4

###
GET {{api}}/count

###
POST {{api}}
Content-Type: application/json

{
  "title": "I must create a website",
  "description": "Using wordpress"
}

###
DELETE {{api}}/3

###
PUT {{api}}/1
Content-Type: application/json

{
  "title": "I have to dinner",
  "description": "Using wordpress"
}
